//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMonoASP
{
	using System;
	using System.Web;
	using System.Web.UI;

	public partial class Default : System.Web.UI.Page
	{
		protected void btnSubmit_Click(object sender, EventArgs args)
		{

		}



		protected void btnReset_Click(object sender, EventArgs args)
		{
			txtEmail.text = "";

		}

	}
}

